import logo from "../assets/logos/tiki-logo.svg";
import icon_search from "../assets/icons/icon_search.svg";
import header_home from "../assets/icons/header_home.svg";
import header_account from "../assets/icons/header_account.svg";
import header_img_Cart from "../assets/icons/header_img_Cart.svg";
import nav_discount from "../assets/icons/navbar_header_icons/nav_discount.svg";
import nav_exchange from "../assets/icons/navbar_header_icons/nav_exchange.svg";
import nav_fast_delivery from "../assets/icons/navbar_header_icons/nav_fast_delivery.svg";
import nav_freeship from "../assets/icons/navbar_header_icons/nav_freeship.svg";
import nav_real from "../assets/icons/navbar_header_icons/nav_real.svg";
import nav_refund from "../assets/icons/navbar_header_icons/nav_refund.svg";
import bo_cong_thuong_2 from "../assets/icons/footer_icons/bo-cong-thuong-2.svg";
import bo_cong_thuong from "../assets/icons/footer_icons/bo-cong-thuong.svg";
import link from "../assets/icons/footer_icons/Link.svg";
import tikinow from "../assets/icons/footer_icons/tikinow-icon.svg";
import facebook from "../assets/icons/footer_icons/facebook.svg";
import youtobe from "../assets/icons/footer_icons/youtobe.svg";
import zalo from "../assets/icons/footer_icons/zalo.svg";
import app_store from "../assets/icons/footer_icons/app_store.svg";
import qr from "../assets/icons/footer_icons/qr.svg";
import gg_play from "../assets/icons/footer_icons/gg_play.svg";

//payment
import atm_pay from "../assets/icons/footer_icons/atm_pay.svg";
import vn_pay from "../assets/icons/footer_icons/vn_pay.svg";
import cash_pay from "../assets/icons/footer_icons/cash_pay.svg";
import installment_pay from "../assets/icons/footer_icons/installment_pay.svg";
import jcb_pay from "../assets/icons/footer_icons/jcb_pay.svg";
import mastercard_pay from "../assets/icons/footer_icons/mastercard_pay.svg";
import momo_pay from "../assets/icons/footer_icons/momo_pay.svg";
import tiki_pay from "../assets/icons/footer_icons/tiki_pay.svg";
import viettel_pay from "../assets/icons/footer_icons/viettel_pay.svg";
import visa_pay from "../assets/icons/footer_icons/visa_pay.svg";
import zalo_pay from "../assets/icons/footer_icons/zalo_pay.svg";
import next_icon from "../assets/icons/next_icon.svg";
import dropup from "../assets/icons/dropup.svg";
import english_books from "../assets/icons/english_books.svg";
import vietnames_book from "../assets/icons/vietnames_book.svg";
import souvenir from "../assets/icons/souvenir.svg";
import calculator from "../assets/icons/calculator.svg";
import now from "../assets/icons/now.svg";
import top_deal from "../assets/icons/top_deal.svg";
import freeship_extra from "../assets/icons/freeship_extra.svg";
import star_fullfill from "../assets/icons/star_fullfill.svg";
import star_notfill from "../assets/icons/star_notfill.svg";
import arrow_left from "../assets/icons/arrow_left.svg";
import arrow_right from "../assets/icons/arrow_right.svg";
import item_carousel from "../assets/icons/item_carousel.svg";
import carousel_navigate from "../assets/icons/carousel_navigate.svg";
import carousel_navigate_active from "../assets/icons/carousel_navigate_active.svg";
import book1 from "../assets/icons/book1.svg";
import book2 from "../assets/icons/book2.svg";
import book3 from "../assets/icons/book3.svg";

export {book1};
export {book2};
export {book3};
export {carousel_navigate};
export {carousel_navigate_active};
export {item_carousel};
export {arrow_left};
export {arrow_right};
export {now};
export {top_deal};
export {freeship_extra};
export {star_fullfill};
export {star_notfill};
export {logo};
export {english_books};
export {vietnames_book};
export {souvenir};
export {calculator};
export {dropup};
export {next_icon};
export {icon_search};
export {header_home};
export {header_account};
export {header_img_Cart};
export {nav_discount};
export {nav_exchange};
export {nav_fast_delivery};
export {nav_freeship};
export {nav_real};
export {nav_refund};
export {bo_cong_thuong_2};
export {bo_cong_thuong};
export {link};
export {tikinow};
export {facebook};
export {youtobe};
export {zalo};
export {app_store};
export {qr};

export {cash_pay};
export {gg_play};
export {installment_pay};
export {jcb_pay};
export {mastercard_pay};
export {momo_pay};
export {tiki_pay};
export {viettel_pay};
export {visa_pay};
export {zalo_pay};
export {atm_pay};
export {vn_pay};

