import logo from "../assets/logos/tiki-logo.svg";
import icon_search from "../assets/icons/icon_search.svg";
import header_home from "../assets/icons/header_home.svg";
import header_account from "../assets/icons/header_account.svg";
import header_img_Cart from "../assets/icons/header_img_Cart.svg";
import nav_discount from "../assets/icons/navbar_header_icons/nav_discount.svg";
import nav_exchange from "../assets/icons/navbar_header_icons/nav_exchange.svg";
import nav_fast_delivery from "../assets/icons/navbar_header_icons/nav_fast_delivery.svg";
import nav_freeship from "../assets/icons/navbar_header_icons/nav_freeship.svg";
import nav_real from "../assets/icons/navbar_header_icons/nav_real.svg";
import nav_refund from "../assets/icons/navbar_header_icons/nav_refund.svg";
import bo_cong_thuong_2 from "../assets/icons/footer_icons/bo-cong-thuong-2.svg";
import bo_cong_thuong from "../assets/icons/footer_icons/bo-cong-thuong.svg";
import link from "../assets/icons/footer_icons/Link.svg";
import tikinow from "../assets/icons/footer_icons/tikinow-icon.svg";
import facebook from "../assets/icons/footer_icons/facebook.svg";
import youtobe from "../assets/icons/footer_icons/youtobe.svg";
import zalo from "../assets/icons/footer_icons/zalo.svg";
import app_store from "../assets/icons/footer_icons/app_store.svg";
import qr from "../assets/icons/footer_icons/qr.svg";
import gg_play from "../assets/icons/footer_icons/gg_play.svg";

//payment
import atm_pay from "../assets/icons/footer_icons/atm_pay.svg";
import vn_pay from "../assets/icons/footer_icons/vn_pay.svg";
import cash_pay from "../assets/icons/footer_icons/cash_pay.svg";
import installment_pay from "../assets/icons/footer_icons/installment_pay.svg";
import jcb_pay from "../assets/icons/footer_icons/jcb_pay.svg";
import mastercard_pay from "../assets/icons/footer_icons/mastercard_pay.svg";
import momo_pay from "../assets/icons/footer_icons/momo_pay.svg";
import tiki_pay from "../assets/icons/footer_icons/tiki_pay.svg";
import viettel_pay from "../assets/icons/footer_icons/viettel_pay.svg";
import visa_pay from "../assets/icons/footer_icons/visa_pay.svg";
import zalo_pay from "../assets/icons/footer_icons/zalo_pay.svg";

export {logo};
export {icon_search};
export {header_home};
export {header_account};
export {header_img_Cart};
export {nav_discount};
export {nav_exchange};
export {nav_fast_delivery};
export {nav_freeship};
export {nav_real};
export {nav_refund};
export {bo_cong_thuong_2};
export {bo_cong_thuong};
export {link};
export {tikinow};
export {facebook};
export {youtobe};
export {zalo};
export {app_store};
export {qr};

export {cash_pay};
export {gg_play};
export {installment_pay};
export {jcb_pay};
export {mastercard_pay};
export {momo_pay};
export {tiki_pay};
export {viettel_pay};
export {visa_pay};
export {zalo_pay};
export {atm_pay};
export {vn_pay};

